Port SUSE's own .spec file

diff --git a/packages/suse/cloud-init.spec.in b/packages/suse/cloud-init.spec.in
--- a/packages/suse/cloud-init.spec.in
+++ b/packages/suse/cloud-init.spec.in
@@ -1,4 +1,23 @@
 ## template: jinja
+#
+# spec file for package cloud-init
+#
+# Copyright (c) 2021 SUSE LINUX Products GmbH, Nuernberg, Germany.
+#
+# All modifications and additions to the file contributed by third parties
+# remain the property of their copyright owners, unless otherwise agreed
+# upon. The license for this file, and modifications and additions to the
+# file, is the same license as for the pristine package itself (unless the
+# license for the pristine package is not an Open Source License, in which
+# case the license is the MIT License). An "Open Source License" is a
+# license that conforms to the Open Source Definition (Version 1.9)
+# published by the Open Source Initiative.
+
+# Please submit bugfixes or comments via http://bugs.opensuse.org/
+#
+# change this whenever config changes incompatible
+%global configver 0.7
+%global __python /usr/bin/python3
 
 # See: http://www.zarb.org/~jasonc/macros.php
 # Or: http://fedoraproject.org/wiki/Packaging:ScriptletSnippets
@@ -8,124 +27,207 @@ Name:           cloud-init
 Version:        {{rpm_upstream_version}}
 Release:        1{{subrelease}}%{?dist}
 Summary:        Cloud instance init scripts
-
 Group:          System/Management
 License:        Dual licensed GPLv3 or Apache 2.0
 URL:            http://launchpad.net/cloud-init
 
-Source0:        {{archive_name}}
-BuildRoot:      %{_tmppath}/%{name}-%{version}-build
+Source0:        %{name}-%{version}.tar.gz
+Source1:        rsyslog-cloud-init.cfg
+Patch1:        datasourceLocalDisk.patch
+# FIXME (lp#1812117)
+Patch2:        cloud-init-write-routes.patch
+# FIXME (lp#1849296)
+Patch3:        cloud-init-break-resolv-symlink.patch
+# FIXME no proposed solution
+Patch4:        cloud-init-sysconf-path.patch
+# FIXME (lp#1860164)
+Patch5:        cloud-init-no-tempnet-oci.patch
+# FIXME https://github.com/canonical/cloud-init/pull/857
+Patch6:        cloud-init-purge-cache-py-ver-change.patch
+# FIXME https://github.com/canonical/cloud-init/commit/899bfaa9d6bfab1db0df99257628ca1f6febff60
+Patch7:        cloud-init-update-test-characters-in-substitution-unit-test.patch
 
-BuildArch:      noarch
-
-%global __python /usr/bin/python3
-
-{% for r in buildrequires %}
-BuildRequires:        {{r}}
+{% for r in buildrequires -%}
+    BuildRequires:        {{r}}
 {% endfor %}
 
 # Install pypi 'dynamic' requirements
-{% for r in requires %}
-Requires:       {{r}}
+{% for r in requires -%}
+    Requires:       {{r}}
 {% endfor %}
 
 # Custom patches
-{% for p in patches %}
-Patch{{loop.index0}}: {{p}}
+{% for p in patches -%}
+    Patch{{loop.index0 + 7}}: {{p}}
 {% endfor %}
+
+%if 0%{?is_opensuse}
+BuildRequires:  openSUSE-release
+%else
+BuildRequires:  sles-release
+%endif
+
+BuildRoot:      %{_tmppath}/%{name}-%{version}-build
+%define         docdir %{_defaultdocdir}/%{name}
+%ifarch %ix86 x86_64
+Requires:       dmidecode
+%endif
+%define initsys systemd
+BuildRequires: pkgconfig(systemd)
+%{?systemd_requires}
+%if 0%{?suse_version} && 0%{?suse_version} == 1220
+%define systemd_prefix /lib
+%else
+%define systemd_prefix /usr/lib
+%endif
 
 %description
 Cloud-init is a set of init scripts for cloud instances.  Cloud instances
 need special scripts to run during initialization to retrieve and install
 ssh keys and to let the user run various scripts.
 
-%prep
-%setup -q -n {{source_name}}
+%package config-suse
+Summary:        Configuration file for Cloud node initialization tool
+Provides:	    cloud-init-config = %configver
+Group:          System/Management
+Conflicts:	    otherproviders(cloud-init-config)
 
-# Custom patches activation
-{% for p in patches %}
-%patch{{loop.index0}} -p1
-end for
+%description config-suse
+This package contains the product specific configuration file
+for cloud-init.
+
+%package doc
+Summary:        Cloud node initialization tool - Documentation
+Group:          System/Management
+Recommends:     cloud-init = %{version}
+
+%description doc
+Cloud-init is an init script that initializes a cloud node (VM)
+according to the fetched configuration data from the admin node.
+
+Documentation and examples for cloud-init tools
+
+%prep
+%setup -q
+%patch1 -p0
+%patch2
+%patch3
+%patch4
+%patch5
+%patch6
+%patch7 -p1
+{% for p in patches -%}
+    %patch{{loop.index0 + 7}} -p1
+    end for
 {% endfor %}
+
+# patch in the full version to version.py
+version_pys=$(find . -name version.py -type f)
+[ -n "$version_pys" ] ||
+{ echo "failed to find 'version.py' to patch with version." 1>&2; exit 1; }
+sed -i "s,@@PACKAGED_VERSION@@,%{version}-%{release}," $version_pys
 
 %build
 %{__python} -m pip install -q build
 %{__python} -m build
 
+%check
+## Ignore test failure currently not doing anything with opennebula
+rm -v tests/unittests/test_datasource/test_opennebula.py
+make unittest
+
 %install
 %{__python} setup.py install \
-            --root=%{buildroot} --prefix=%{_prefix} \
-            --record-rpm=INSTALLED_FILES \
-            --init-system=systemd
+--root=%{buildroot} --prefix=%{_prefix} \
+--install-lib=%{python3_sitelib} --init-system=%{initsys}
 
-# Move udev rules
+find %{buildroot} \( -name .gitignore -o -name .placeholder \) -delete
+# from debian install script
+for x in "%{buildroot}%{_bindir}/"*.py; do
+[ -f "${x}" ] && mv "${x}" "${x%.py}"
+done
+mkdir -p %{buildroot}%{_localstatedir}/lib/cloud
+# move documentation
+mkdir -p %{buildroot}%{_defaultdocdir}
+mv %{buildroot}%{_datadir}/doc/%{name} %{buildroot}%{_defaultdocdir}
+# man pages
+mkdir -p %{buildroot}%{_mandir}/man1
+mv doc/man/* %{buildroot}%{_mandir}/man1
+# copy the LICENSE
+mkdir -p %{buildroot}%{_defaultlicensedir}/%{name}
+cp LICENSE %{buildroot}%{_defaultlicensedir}/%{name}
+cp LICENSE-GPLv3 %{buildroot}%{_defaultlicensedir}/%{name}
+# Set the distribution indicator
+%if 0%{?suse_version}
+%if 0%{?is_opensuse}
+sed -i s/suse/opensuse/ %{buildroot}/%{_sysconfdir}/cloud/cloud.cfg
+%else
+sed -i s/suse/sles/ %{buildroot}/%{_sysconfdir}/cloud/cloud.cfg
+%endif
+%endif
+mkdir -p %{buildroot}/%{_sysconfdir}/rsyslog.d
 mkdir -p %{buildroot}/usr/lib/udev/rules.d/
-mv %{buildroot}/lib/udev/rules.d/* %{buildroot}/usr/lib/udev/rules.d/
+cp -a %{SOURCE1} %{buildroot}/%{_sysconfdir}/rsyslog.d/21-cloudinit.conf
+mv %{buildroot}/lib/udev/rules.d/66-azure-ephemeral.rules %{buildroot}/usr/lib/udev/rules.d/
+
+# remove debian/ubuntu specific profile.d file (bnc#779553)
+rm -f %{buildroot}%{_sysconfdir}/profile.d/Z99-cloud-locale-test.sh
 
 # Remove non-SUSE templates
 rm %{buildroot}/%{_sysconfdir}/cloud/templates/*.debian.*
 rm %{buildroot}/%{_sysconfdir}/cloud/templates/*.redhat.*
 rm %{buildroot}/%{_sysconfdir}/cloud/templates/*.ubuntu.*
 
-# Move documentation
-mkdir -p %{buildroot}/%{_defaultdocdir}
-mv %{buildroot}/usr/share/doc/cloud-init %{buildroot}/%{_defaultdocdir}
-for doc in LICENSE ChangeLog requirements.txt; do
-   cp ${doc} %{buildroot}/%{_defaultdocdir}/cloud-init
-done
-
-# Remove duplicate files
+# remove duplicate files
 %if 0%{?suse_version}
-   %fdupes %{buildroot}/%{python_sitelib}
+%fdupes %{buildroot}%{python3_sitelib}
 %endif
 
-mkdir -p %{buildroot}/var/lib/cloud
-
-# patch in the full version to version.py
-version_pys=$(cd "%{buildroot}" && find . -name version.py -type f)
-[ -n "$version_pys" ] ||
-   { echo "failed to find 'version.py' to patch with version." 1>&2; exit 1; }
-( cd "%{buildroot}" &&
-  sed -i "s,@@PACKAGED_VERSION@@,%{version}-%{release}," $version_pys )
-
-%postun
-%insserv_cleanup
-
 %files
-
-# Program binaries
-%{_bindir}/cloud-init*
-%{_bindir}/cloud-id*
-
-# There doesn't seem to be an agreed upon place for these
-# although it appears the standard says /usr/lib but rpmbuild
-# will try /usr/lib64 ??
-/usr/lib/cloud-init/uncloud-init
-/usr/lib/cloud-init/write-ssh-key-fingerprints
-/usr/lib/cloud-init/ds-identify
-
-# udev rules
-/usr/lib/udev/rules.d/66-azure-ephemeral.rules
-
-
-# Docs
-%doc %{_defaultdocdir}/cloud-init/*
-
-# Configs
-%config(noreplace) %{_sysconfdir}/cloud/cloud.cfg
-%dir               %{_sysconfdir}/cloud/cloud.cfg.d
-%config(noreplace) %{_sysconfdir}/cloud/cloud.cfg.d/*.cfg
-%config(noreplace) %{_sysconfdir}/cloud/cloud.cfg.d/README
-%dir               %{_sysconfdir}/cloud/templates
-%config(noreplace) %{_sysconfdir}/cloud/templates/*
-
-# Bash completion script
-%{_datadir}/bash-completion/completions/cloud-init
-
+%defattr(-,root,root)
+%license LICENSE LICENSE-GPLv3
+%{_bindir}/cloud-id
+%{_bindir}/cloud-init
+%{_bindir}/cloud-init-per
+%dir %{_sysconfdir}/cloud
+%config(noreplace) %{_sysconfdir}/cloud/cloud.cfg.d
+%config(noreplace) %{_sysconfdir}/cloud/templates
 %{_sysconfdir}/dhcp/dhclient-exit-hooks.d/hook-dhclient
 %{_sysconfdir}/NetworkManager/dispatcher.d/hook-network-manager
+%{_mandir}/man*/*
+%if 0%{?suse_version} && 0%{?suse_version} < 1500
+%dir %{_datadir}/bash-completion
+%dir %{_datadir}/bash-completion/completions
+%endif
+%{_datadir}/bash-completion/completions/cloud-init
+%{python3_sitelib}/cloudinit
+%{python3_sitelib}/cloud_init-%{version}-py%{py3_ver}.egg-info
+%{_prefix}/lib/cloud-init
+%{systemd_prefix}/systemd/system-generators/cloud-init-generator
+%{systemd_prefix}/systemd/system/cloud-config.service
+%{systemd_prefix}/systemd/system/cloud-config.target
+%{systemd_prefix}/systemd/system/cloud-init-local.service
+%{systemd_prefix}/systemd/system/cloud-init.service
+%{systemd_prefix}/systemd/system/cloud-init.target
+%{systemd_prefix}/systemd/system/cloud-final.service
+%dir %{_sysconfdir}/rsyslog.d
+%{_sysconfdir}/rsyslog.d/21-cloudinit.conf
+/usr/lib/udev/rules.d/66-azure-ephemeral.rules
+%dir %attr(0755, root, root) %{_localstatedir}/lib/cloud
+%dir %{docdir}
+%dir /etc/NetworkManager
+%dir /etc/NetworkManager/dispatcher.d
+%dir /etc/dhcp
+%dir /etc/dhcp/dhclient-exit-hooks.d
 
-# Python code is here...
-%{python_sitelib}/*
+%files config-suse
+%defattr(-,root,root)
+%config(noreplace) %{_sysconfdir}/cloud/cloud.cfg
 
-/var/lib/cloud
+%files doc
+%defattr(-,root,root)
+%{docdir}/examples/*
+%{docdir}/*.txt
+%dir %{docdir}/examples
+
+%changelog
